### ISSUE TITLE
Where to start with this? 

### ISSUE THREAD

**Issue by geo7** [judepereira/44a#1]
I just bumped into this searching CLion as I think I might try it soon (having never done C++ before) and would like to try OpenFrameworks (I've done a little Processing). 

I was just wondering if you could suggest any decent 'starting points' with this in mind? 

(opened and closed this as it's not _really_ an issue)

**Comment by judepereira** [comment]
You could try this book: http://www.amazon.com/Mastering-openFrameworks-Creative-Coding-Demystified/dp/1849518041
