### ISSUE TITLE
'unordered_map' file not found

### ISSUE THREAD

**Issue by TechMaster** [judepereira/44a#2]
I tried to use your 44a project and compile using CLion 1.2, on MacOSX 10.10.5 and XCode 7.1.

I encounter 'fatal error: 'unordered_map' file not found'

I created another simple Clion project that include unordered_map. Compilation is successful.

What should I do?

Thanks,

**Comment by judepereira** [comment]
Hey @TechMaster, I don't have a solution to this, as I've never faced it. Moreover, I moved from using CLion to AppCode (since it plays nicely with all Xcode projects).
