### ISSUE TITLE
0.9.0

### ISSUE THREAD

**Issue by schwittlick** [judepereira/44a#5]
hey, this is great, i dont have much experience regarding cmake, but I wonder when I'd try to use of0.9.0 with this, it wouldn't work, right?

thanks,
marcel

**Comment by judepereira** [comment]
Hey @mrzl, we've already begun work on 0.9.0. We've patched the project generator, along with cmake support for a few addons. You can follow the progress here:
https://forum.openframeworks.cc/t/are-there-any-plan-for-supporting-clion/17188/
